/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaBot;

import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author arafa
 */
public class bot extends javax.swing.JFrame {
    
    String greet="                         Hello Sir I'm your personal Bot. Lets chat.\n";

    /**
     * Creates new form bot
     */
    public bot() {
        initComponents();
        outputbox.setText(greet);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        msgbox = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputbox = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        inputbox = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KiloByte KB 1.0 Silver");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msgbox.setBackground(new java.awt.Color(0, 0, 0));

        outputbox.setEditable(false);
        outputbox.setBackground(new java.awt.Color(255, 255, 255));
        outputbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        outputbox.setForeground(new java.awt.Color(0, 0, 0));
        outputbox.setLineWrap(true);
        outputbox.setTabSize(0);
        outputbox.setWrapStyleWord(true);
        jScrollPane1.setViewportView(outputbox);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Algerian", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Java Personal Bot");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HELP2.GIF"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gtk-add.png"))); // NOI18N

        inputbox.setBackground(new java.awt.Color(255, 255, 255));
        inputbox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        inputbox.setToolTipText("Your Text Here");
        inputbox.setAutoscrolls(false);
        inputbox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputbox.setDragEnabled(true);
        inputbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputboxActionPerformed(evt);
            }
        });
        inputbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputboxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputboxKeyTyped(evt);
            }
        });

        btnsend.setBackground(new java.awt.Color(0, 80, 178));
        btnsend.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        btnsend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_web_9_3924904 (1).png"))); // NOI18N
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Java1.png"))); // NOI18N

        javax.swing.GroupLayout msgboxLayout = new javax.swing.GroupLayout(msgbox);
        msgbox.setLayout(msgboxLayout);
        msgboxLayout.setHorizontalGroup(
            msgboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgboxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(msgboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msgboxLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msgboxLayout.createSequentialGroup()
                        .addComponent(inputbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsend, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        msgboxLayout.setVerticalGroup(
            msgboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msgboxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(msgboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(msgboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(msgboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(msgboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(msgbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 500, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    LocalDate date = LocalDate.now();
    LocalTime time = LocalTime.now();

    private void inputboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputboxActionPerformed

        String gtext = inputbox.getText().toLowerCase();
        outputbox.append("-->You: " + gtext + "\n");
        inputbox.setText(" ");
      //Greetings panel
        if (gtext.contains("hi")) {
            jbot("Hi sir!");
        } else if (gtext.contains("how")) {
            jbot("Fine sir. And you?");
        } else if (gtext.contains("fine")) {
            jbot("Good to hear that");
        }
        //time date panel
        else if (gtext.contains("date")) {
            jbot("Date is: " + date);
        } else if (gtext.contains("time")) {
            jbot("Time is: " + time);
        } 
        //version panel
        else if (gtext.contains("name")) {
            jbot("My Name is Kilobyte");
        } else if(gtext.contains("version")){
            jbot("My version is: KB 1.0 Silver");
        }
        else if(gtext.contains("about")){
            
            jbot("My name is Kilobyte"+"\n Version: KB 1.0 Silver"+"\n I'm a SuperBot Created by: Arafat Hossain Ar" );
        } else if(gtext.contains("creator")){
            jbot("My creator name is: Arafat Hossain Ar");
            
        }
        //Java panel
        else if (gtext.contains("java")) {
            jbot("Java is a object oriented programming language and computing platform first released by Sun Microsystems in 1995. ");
        } 
        //utility panel
        else if (gtext.contains("calculator")) {
            jbot("Opening Calculator for you sir........");
            Calculator cal = new Calculator();
            cal.setVisible(true);
            cal.pack();
            cal.setLocationRelativeTo(null);
            cal.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        } 
        //other information
        
        else if(gtext.contains("facebook")){
            jbot("Facebook or Facebook is a website for the Worldwide Social Interaction System, which was established on February 7, 2015. It can be a free member. It is owned by Facebook Inc.");
            
        }else if(gtext.contains("google")){
            jbot("Google Search is the largest search engine on the web. Google's goal is to \"make all the information in the world organized and make it publicly available.\" This is the largest search engine. Google receives about 10 million search requests daily through its various services.");
        }else if(gtext.contains("internet")){
            jbot("The Internet is not synonymous with World Wide Web. The Internet is a massive network of networks, a networking infrastructure. It connects millions of computers together globally, forming a network in which any computer can communicate with any other computer as long as they are both connected to the Internet");
        }
        
        //last greetings
        else if (gtext.contains("thanks")) {
            jbot("Welcome bro");
        } else if (gtext.contains("night")) {
            jbot("Good Night too bro. Have Sweet a Dream");
        } else if (gtext.contains("allah")) {
            jbot("Allah Hafez");
        } 
        //defualt command panel
        else {
            final int num = 3;
            double r = Math.random();
            int rand = (int) (r * num);
            String bot = "";
            if (rand == 0) {
                jbot("I Don't Understand");
            } else if (rand == 1) {
                jbot("Sorry, I Don't Understand");
            } else if (rand == 2) {
                jbot("I'm Not Programmed to Response that");
            } else if (rand == 3) {
                jbot("Come Again Please");
            }
        }


    }//GEN-LAST:event_inputboxActionPerformed

    public void chat1() {;

    }

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed

        String gtext = inputbox.getText().toLowerCase();
        outputbox.append("Arafat >> " + gtext + "\n");
        inputbox.setText(" ");
        if (gtext.contains("hi")) {
            jbot("Hi");
        } else if (gtext.contains("how")) {
            jbot("Fine Bro. And You?");
        } else if (gtext.contains("fine")) {
            jbot("Good to hear that");
        } else if (gtext.contains("date")) {
            jbot("Date is: " + date);
        } else if (gtext.contains("time")) {
            jbot("Time is: " + time);
        } else if (gtext.contains("name")) {
            jbot("My Name is Kilobyte");
        } else if (gtext.contains("java")) {
            jbot("Java is a object oriented programming language and computing platform first released by Sun Microsystems in 1995. ");
        } else if (gtext.contains("thanks")) {
            jbot("Welcome bro");
        } else if (gtext.contains("night")) {
            jbot("Good Night too bro. Have Sweet a Dream");
        } else if (gtext.contains("allah")) {
            jbot("Allah Hafez");
        } else {
            final int num = 3;
            double r = Math.random();
            int rand = (int) (r * num);
            String bot = "";
            if (rand == 0) {
                jbot("I Don't Understand");
            } else if (rand == 1) {
                jbot("Sorry, I Don't Understand");
            } else if (rand == 2) {
                jbot("I'm Not Programmed to Response that");
            } else if (rand == 3) {
                jbot("Come Again Please");
            }
        }

    }//GEN-LAST:event_btnsendActionPerformed

    private void jbot(String string) {
        outputbox.append("-->Kilobyte: " + string + "\n");

    }

    private void inputboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputboxKeyPressed


    }//GEN-LAST:event_inputboxKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JOptionPane.showMessageDialog(this, "All Right Reserved By Arafat Hossain Ar");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputboxKeyTyped


    }//GEN-LAST:event_inputboxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsend;
    public static javax.swing.JTextField inputbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel msgbox;
    private javax.swing.JTextArea outputbox;
    // End of variables declaration//GEN-END:variables

}
